#define STARTUP_TIMEOUT             6000
#define SECURITY_TIMEOUT            3000
#define FAKE_LEADER_TIMEOUT         5000
#define FAKE_LEADER_TO_FILM_TIMEOUT 1000
#define FAKE_LEADER_INTERVAL        2000
#define FAKE_FILM_TIMEOUT           1000
